import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import { Separator } from "@/components/ui/separator"
import ApolloProvider from '@/components/ApolloProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-4`}>
        <ApolloProvider>
          <Header />
          <Separator className='mb-6' />
          <main>{children}</main>
        </ApolloProvider>
      </body>
    </html>
  )
}
